<?php

namespace AppBundle\Repository;

/**
 * clienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clienteRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findOneByName($name)
{
    $query = $this->getEntityManager()->createQuery(
            'SELECT c FROM AppBundle:Cliente c
            WHERE c.nombre = :nombre'
        )->setParameter('nombre', $nombre);
 
    try
    {
        return $query->getSingleResult();
    }
    catch (\Doctrine\ORM\NoResultException $e)
    {
        return null;
    }
}
}
